### ISSUE TITLE
Invalid texture data in twobuildings.city.json

### ISSUE THREAD

**Issue by I-Sokolov** [cityjson/website#14]
I think texture data is invalid in the example twobuildings.city.json.
"geometry" has "texture" member, but "appearance" object is missed

**Comment by hugoledoux** [comment]
You're totally right, somehow I only removed the `"appearance"` property and left the textures in the objects...

I'll remove now (`cjio myfile.json textures_remove save new.json` does the trick btw).

Thanks!
