### ISSUE TITLE
Link to a section of 'latest' specs

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/website#2]
I would like to use permanent link to a specific section of latest version of the specs:

For example: https://www.cityjson.org/specs/latest/#transform-object

But this redirects me to the root: https://www.cityjson.org/specs/1.0.0

While using a specific version works as expected: https://www.cityjson.org/specs/1.0.0/#transform-object

**Comment by hugoledoux** [comment]
I wanted to do this, but I don't know how 🤷‍♂️

One option is to have /specs/#transform-object as the latest, and for previous version the number is added.

**Comment by balazsdukai** [comment]
Yes, this is good: "One option is to have /specs/#transform-object as the latest, and for previous version the number is added."

**Comment by hugoledoux** [comment]
fixed in 0a6c3fcbd2eb1dce6e4500f3e050f88478476d61
