### ISSUE TITLE
Section 3 (Geometry) of specs should mention GeometryInstances

### ISSUE THREAD

**Issue by liberostelios** [cityjson/website#3]
Currently, the Geometry section of the specification doesn't list GeometryInstances as one type of geometries. This is misleading as someone that doesn't read the whole document might be confused about what has to be done in order to support all possible geometry types.

I think just a simple warning in section 3 that references section 6 as an exception would solve the issue.

**Comment by kenohori** [comment]
I think moving it to section 3 would be even better.

**Comment by hugoledoux** [comment]
fixed for v1.01:

https://github.com/tudelft3d/cityjson/commit/57645735bb97901e0391d46e29ba4a655f955fb6
