### ISSUE TITLE
Datasets with errors

### ISSUE THREAD

**Issue by Athelena** [cityjson/website#6]
I know we provide several datasets for download that were converted from CityGML datasets that had errors, therefore the CityJSON datasets have errors too. I know it's not our job to fix this but we should flag it. As a newbie I would be studying the datasets intensely and errors would confuse me a lot.

**Comment by liberostelios** [comment]
Indeed. I think people would falsely assume that those datasets are examples to follow when implementing stuff and it should be clear that they are real datasets with biased decisions made and, even more, with issues.

A clear disclaimer/explanation I think is necessary.

**Comment by Athelena** [comment]
Any opinions here? I'm happy to update the website, just want to see if others agree on this...

**Comment by hugoledoux** [comment]
The question is: what errors do you mean?

If there are no CityJSON errors related to the schema, then yeah maybe a small warning.

But geometric errors? This opens the door to us screening and approving all datasets?

**Comment by Athelena** [comment]
In this case it's geometric errors. I think it's important to remind people of this. Especially when learning something new. I'd hate to be struggling to learn and waste a ton of time before I realise it's due to a geometric error. Since we **know** there are errors why not warn? We're not screening but acknowledging IMO.

**Comment by hugoledoux** [comment]
Yeah, okay. So who runs val3dity and add a column to reports errors?

**Comment by hugoledoux** [comment]
All right, I'll do it, my cityjson.org day it is...

**Comment by Athelena** [comment]
I'm not sure I understand what you mean exactly, but glad you're motivated

**Comment by hugoledoux** [comment]
4313dbdf43402f4882823ad6e3e002b822f663f0
